### ISSUE TITLE
tying to compile source on ubuntu 16.4 

### ISSUE THREAD

**Issue by olalawal** [Pigeoncoin/pigeoncoin#15]
I get this during the build , any ideas ?

 CXXLD    pigeond
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libpigeon_crypto.a: error adding symbols: Bad value

**Comment by spiderywookie** [comment]
I had to add -fPIC to both CXXFLAGS and CPPFLAGS for the build to succeed.

Just curious, why are you compiling via gitian instead of the standard make tools?

**Comment by olalawal** [comment]
hmm i  just followed the instrucctions in the doc
./autogen.sh
./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX
make

I assumed since this a fork of raven it should work the same  way, what do you mean standard make tools.

extracted your current git repo and then tried to build

**Comment by R3D5H1RT** [comment]
sudo ./autogen.sh
sudo ./configure --enable-cxx --disable-shared --without-gui --with-pic --prefix=$BDB_PREFIX
make

**Comment by olalawal** [comment]
@r3d5h1rt what does the —withoute-gui flag do

**Comment by olalawal** [comment]
@R3D5H1RT - same error
 
AR       leveldb/libleveldb.a
  CXX      leveldb/port/leveldb_libleveldb_sse42_a-port_posix_sse.o
  AR       leveldb/libleveldb_sse42.a
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
  CXXLD    pigeond
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libpigeon_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3775: recipe for target 'pigeond' failed
make[2]: *** [pigeond] Error 1
make[2]: Leaving directory '/home/pool/compil/pigeoncoin/src'
Makefile:9954: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pool/compil/pigeoncoin/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
pool@192:~/compil/pigeoncoin$

**Comment by olalawal** [comment]
ok the correct configure line is the same one from ravencoin

./configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX CXXFLAGS="-fPIC" CPPFLAGS="-fPIC"

this allowed me to build

I also had to delete and reclone to repo, make clean was not enough to salvage the previous builds

**Comment by spiderywookie** [comment]
Apologies I completely misread your initial post whilst I was in the middle of working on something.

Look over this guide - it has lots of information about the configure flags.
https://github.com/Pigeoncoin/pigeoncoin/blob/master/doc/build-unix.md

When I build the repo locally (and not with gitian) I use the following:

./autogen.sh
./configure --enable-cxx --disable-shared --with-pic CXXFLAGS="-fPIC -O" CPPFLAGS="-fPIC -O"
make -j 4   (note the -j 4 is optional and enables multi thread compiling)
