### ISSUE TITLE
Http link in 'About Pigeon core' returns 404

### ISSUE THREAD

**Issue by muhamati** [Pigeoncoin/pigeoncoin#18]
- Linux wallet 0.15.99.3 
- About Pigeon core (small separate window - links, licenses, ...)
- click link under the "The source code is available from https://github.com/PigeonProject/Pigeoncoin."

Click results in a 404 response from a web server. (Directory listing is blocked globaly on a web server?)

**Comment by lukepighetti** [comment]
Hi @muhamati can you please author a pull request to resolve this issue

**Comment by muhamati** [comment]
hkfytdrfg
