### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by laakie** [Pigeoncoin/pigeoncoin#22]
I can't get this wallet compiled on 3 machines Ubuntu 14.04 And 16.04
Am I missing something here?
already tried --with-fPIC and more,
Nothing seems to work for me.

CXXLD    pigeon-tx
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-bmw.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-echo.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-groestl.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-jh.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-keccak.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-luffa.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-shavite.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-simd.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-sph_hamsi.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-sph_fugue.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-sph_whirlpool.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: crypto/libpigeon_crypto.a(crypto_libpigeon_crypto_a-sph_sha512.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:3771: recipe for target 'pigeon-tx' failed
make[2]: *** [pigeon-tx] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by lukepighetti** [comment]
Hi laakie, check our `Dockerfile` for the steps we take to build.

https://github.com/Pigeoncoin/services/blob/master/pigeon-docker/Dockerfile
